Let's drop support for Go 1.16, since golang.org/x/crypto fails to build too
Error: ../../../go/pkg/mod/golang.org/x/crypto@v0.22.0/ssh/cipher.go:19:2: //go:build comment without // +build comment
Error: ../../../go/pkg/mod/golang.org/x/crypto@v0.22.0/ssh/kex.go:19:2: //go:build comment without // +build comment